## This is the generated configuration file for Headroom.
## See https://github.com/vaclavsvejcar/headroom for more details.

## Defines the behaviour how to handle license headers, possible options are:
##   - add     = (default) adds license header to files with no existing header
##   - drop    = drops existing license header from without replacement
##   - replace = adds or replaces existing license header
run-mode: add

## Paths to source code files (either files or directories).
source-paths:
  - src/main/scala
  - src/test/scala

## Paths to template files (either files or directories).
template-paths:
  - templates

## Variables (key-value) to replace in templates.
variables:
  name: YouTube History Downloader
  description: Download your full YouTube watch history
  author: Vaclav Svejcar
  year: 2019-2020

